<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="8" passed="0" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-22T12:12:51 CET" name="Invoice Portal TT Application Test" finished-at="2021-09-22T12:19:30 CET" duration-ms="398623">
    <groups>
    </groups>
    <test started-at="2021-09-22T12:12:51 CET" name="End To End Test" finished-at="2021-09-22T12:19:30 CET" duration-ms="398623">
      <class name="com.invoice_portal.testcase.DemandeSignature">
        <test-method is-config="true" signature="SetUp(java.lang.String, java.lang.reflect.Method)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:12:51 CET" name="SetUp" finished-at="2021-09-22T12:13:29 CET" duration-ms="37808" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://localhost:8081/login]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Clique_Voir_Historique(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Clique_Voir_Historique(java.lang.reflect.Method)[pri:3, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:13:29 CET" name="Clique_Voir_Historique" finished-at="2021-09-22T12:14:01 CET" duration-ms="31409" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Clique_Voir_Historique(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.StaleElementReferenceException">
            <message>
              <![CDATA[stale element reference: element is not attached to the page document
  (Session info: chrome=93.0.4577.82)
For documentation on this error, please visit: https://selenium.dev/exceptions/#stale_element_reference
Build info: version: '4.0.0-alpha-6', revision: '5f43a29cfc'
System info: host: 'IMEX', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-34-generic', java.version: '11.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 93.0.4577.82, chrome: {chromedriverVersion: 93.0.4577.63 (ff5c0da2ec0ad..., userDataDir: /tmp/.com.google.Chrome.ZgU6Ze}, goog:chromeOptions: {debuggerAddress: localhost:41819}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 2215187e49af0764a45aefa2a65ad024]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=93.0.4577.82)
For documentation on this error, please visit: https://selenium.dev/exceptions/#stale_element_reference
Build info: version: '4.0.0-alpha-6', revision: '5f43a29cfc'
System info: host: 'IMEX', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.11.0-34-generic', java.version: '11.0.11'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 93.0.4577.82, chrome: {chromedriverVersion: 93.0.4577.63 (ff5c0da2ec0ad..., userDataDir: /tmp/.com.google.Chrome.ZgU6Ze}, goog:chromeOptions: {debuggerAddress: localhost:41819}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 2215187e49af0764a45aefa2a65ad024
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:196)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:129)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:582)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:316)
at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:363)
at com.invoice_portal.testcase.DemandeSignature.Clique_Voir_Historique(DemandeSignature.java:93)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.StaleElementReferenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Clique_Voir_Historique -->
        <test-method is-config="true" signature="tearDown(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:14:01 CET" name="tearDown" finished-at="2021-09-22T12:14:02 CET" duration-ms="470" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Clique_Voir_Historique(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=Clique_Voir_Historique status=FAILURE method=DemandeSignature.Clique_Voir_Historique(java.lang.reflect.Method)[pri:3, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.String, java.lang.reflect.Method)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:14:02 CET" name="SetUp" finished-at="2021-09-22T12:14:37 CET" duration-ms="34940" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://localhost:8081/login]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Non_Signes(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Documents_Non_Signes(java.lang.reflect.Method)[pri:4, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:14:37 CET" name="Documents_Non_Signes" finished-at="2021-09-22T12:15:08 CET" duration-ms="30807" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Non_Signes(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[http://localhost:8081/admin/HistoriqueUploadAnce/ expected:<http://localhost:8081/admin/HistoriqueUploadAnce/> but was:<La page documents non signés non charger>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: http://localhost:8081/admin/HistoriqueUploadAnce/ expected:<http://localhost:8081/admin/HistoriqueUploadAnce/> but was:<La page documents non signés non charger>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at com.invoice_portal.testcase.DemandeSignature.Documents_Non_Signes(DemandeSignature.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Documents_Non_Signes -->
        <test-method is-config="true" signature="tearDown(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:15:08 CET" name="tearDown" finished-at="2021-09-22T12:15:09 CET" duration-ms="1307" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Non_Signes(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=Documents_Non_Signes status=FAILURE method=DemandeSignature.Documents_Non_Signes(java.lang.reflect.Method)[pri:4, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.String, java.lang.reflect.Method)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:15:09 CET" name="SetUp" finished-at="2021-09-22T12:15:44 CET" duration-ms="34387" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://localhost:8081/login]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Supprimes(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Documents_Supprimes(java.lang.reflect.Method)[pri:5, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:15:44 CET" name="Documents_Supprimes" finished-at="2021-09-22T12:16:12 CET" duration-ms="28423" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Supprimes(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[http://localhost:8081/admin/HistoriqueUploadAnce/ expected:<http://localhost:8081/admin/HistoriqueUploadAnce/> but was:<La page documents supprimés non charger>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: http://localhost:8081/admin/HistoriqueUploadAnce/ expected:<http://localhost:8081/admin/HistoriqueUploadAnce/> but was:<La page documents supprimés non charger>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at com.invoice_portal.testcase.DemandeSignature.Documents_Supprimes(DemandeSignature.java:132)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Documents_Supprimes -->
        <test-method is-config="true" signature="tearDown(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:16:13 CET" name="tearDown" finished-at="2021-09-22T12:16:13 CET" duration-ms="488" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Supprimes(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=Documents_Supprimes status=FAILURE method=DemandeSignature.Documents_Supprimes(java.lang.reflect.Method)[pri:5, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.String, java.lang.reflect.Method)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:16:13 CET" name="SetUp" finished-at="2021-09-22T12:16:47 CET" duration-ms="33642" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://localhost:8081/login]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Verifier(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Documents_Verifier(java.lang.reflect.Method)[pri:6, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:16:47 CET" name="Documents_Verifier" finished-at="2021-09-22T12:17:05 CET" duration-ms="18341" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Verifier(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[http://localhost:8081/admin/historiqueVerify expected:<http://localhost:8081/admin/historiqueVerify> but was:<La page documents vérifiés non charger>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: http://localhost:8081/admin/historiqueVerify expected:<http://localhost:8081/admin/historiqueVerify> but was:<La page documents vérifiés non charger>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at com.invoice_portal.testcase.DemandeSignature.Documents_Verifier(DemandeSignature.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Documents_Verifier -->
        <test-method is-config="true" signature="tearDown(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:17:06 CET" name="tearDown" finished-at="2021-09-22T12:17:06 CET" duration-ms="418" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Verifier(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=Documents_Verifier status=FAILURE method=DemandeSignature.Documents_Verifier(java.lang.reflect.Method)[pri:6, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.String, java.lang.reflect.Method)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:17:06 CET" name="SetUp" finished-at="2021-09-22T12:17:43 CET" duration-ms="36565" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://localhost:8081/login]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Non_Verifies(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Documents_Non_Verifies(java.lang.reflect.Method)[pri:7, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:17:43 CET" name="Documents_Non_Verifies" finished-at="2021-09-22T12:18:23 CET" duration-ms="40521" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Non_Verifies(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[http://localhost:8081/admin/historiqueVerify expected:<http://localhost:8081/admin/historiqueVerify> but was:<La page documents non vérifiés non charger>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: http://localhost:8081/admin/historiqueVerify expected:<http://localhost:8081/admin/historiqueVerify> but was:<La page documents non vérifiés non charger>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at com.invoice_portal.testcase.DemandeSignature.Documents_Non_Verifies(DemandeSignature.java:171)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Documents_Non_Verifies -->
        <test-method is-config="true" signature="tearDown(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:18:25 CET" name="tearDown" finished-at="2021-09-22T12:18:25 CET" duration-ms="409" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Non_Verifies(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=Documents_Non_Verifies status=FAILURE method=DemandeSignature.Documents_Non_Verifies(java.lang.reflect.Method)[pri:7, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.String, java.lang.reflect.Method)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:18:25 CET" name="SetUp" finished-at="2021-09-22T12:18:59 CET" duration-ms="33380" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://localhost:8081/login]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Supprimes_pour_verifiés(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Documents_Supprimes_pour_verifiés(java.lang.reflect.Method)[pri:8, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:18:59 CET" name="Documents_Supprimes_pour_verifiés" finished-at="2021-09-22T12:19:29 CET" duration-ms="30553" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Supprimes_pour_verifiés(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[http://localhost:8081/admin/historiqueVerify expected:<http://localhost:8081/admin/historiqueVerify> but was:<La page documents supprimés pour vérifiés non charger>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: http://localhost:8081/admin/historiqueVerify expected:<http://localhost:8081/admin/historiqueVerify> but was:<La page documents supprimés pour vérifiés non charger>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at com.invoice_portal.testcase.DemandeSignature.Documents_Supprimes_pour_verifiés(DemandeSignature.java:193)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Documents_Supprimes_pour_verifiés -->
        <test-method is-config="true" signature="tearDown(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e]" started-at="2021-09-22T12:19:30 CET" name="tearDown" finished-at="2021-09-22T12:19:30 CET" duration-ms="318" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.invoice_portal.testcase.DemandeSignature.Documents_Supprimes_pour_verifiés(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=Documents_Supprimes_pour_verifiés status=FAILURE method=DemandeSignature.Documents_Supprimes_pour_verifiés(java.lang.reflect.Method)[pri:8, instance:com.invoice_portal.testcase.DemandeSignature@7ce3cb8e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.invoice_portal.testcase.DemandeSignature -->
      <class name="com.invoice_portal.testcase.Config">
        <test-method is-config="true" signature="Start()[pri:0, instance:com.invoice_portal.testcase.Config@10e92f8f]" started-at="2021-09-22T12:12:51 CET" name="Start" finished-at="2021-09-22T12:12:51 CET" duration-ms="407" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method is-config="true" signature="End()[pri:0, instance:com.invoice_portal.testcase.Config@10e92f8f]" started-at="2021-09-22T12:19:30 CET" name="End" finished-at="2021-09-22T12:19:31 CET" duration-ms="443" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- End -->
      </class> <!-- com.invoice_portal.testcase.Config -->
    </test> <!-- End To End Test -->
  </suite> <!-- Invoice Portal TT Application Test -->
</testng-results>
